### ISSUE TITLE
Global competitive compensation - how is it measured?

### ISSUE THREAD

**Issue by pablohoffman** [yanirs/established-remote#79]
Hi, I'm co-founder and director at Scrapinghub, one of the companies in the list and I see we're marked as having non competitive global compensation. We have a team of strong technical people and professionals, we're certainly not after "cheap labor". I believe we offer competitive compensation but before I go ahead and submit a pull request, I was wondering how this field is audited. Thanks!

**Comment by Khrol** [comment]
![Screen Shot 2019-04-25 at 16 24 17](https://user-images.githubusercontent.com/3982146/56739133-b612d480-6776-11e9-9f02-7f1f6131f02d.png)

I think it's a good public source. 1.5x diff compared to Amazon Intern.

**Comment by yanirs** [comment]
Thanks for the question, @pablohoffman. As @Khrol has pointed out, the field is populated based on public information. In addition to Glassdoor, I also remember seeing Scrapinghub job ads with a salary range that was pretty low in comparison to salaries in places like the US and Australia. 

To get an idea what globally-competitive compensation looks like, check out [Basecamp's jobs page](https://basecamp.com/about/jobs):

> **Top 10% salaries** - We monitor industry salaries and make sure we’re paying in the top 10%, based on skills and experience, for every position. Salaries are standardized on the San Francisco market.

For a less extreme example that does consider employee location, check out the [Stack Overflow salary calculator](https://stackoverflow.com/company/salary/calculator). Their approach is still competitive, as they would be able to match salaries regardless of where the employee is based.

As it stands, it seems unlikely that Scrapinghub would be able to attract people from tech hubs or from certain countries. For example, based on the available information, I wouldn't apply for a job with Scrapinghub because I'm based in Australia. I'd be happy to update the list if I got your policy wrong or if you have changed it recently.

**Comment by TehShrike** [comment]
I doubt most contributors to this repository know what the top 10% of engineering positions are making.  Basecamp certainly isn't sourcing their numbers from Glassdoor.

"Globally competitive" doesn't convey much – a fairly competitive rate in the midwest wouldn't be tempting to someone in CA or NY, but would be incredibly tempting to an engineer in the EU.

I would rather see salary range for US employees, plus a column with salary range for non-US employees, if applicable.

**Comment by yanirs** [comment]
@TehShrike I don't think anyone has the capacity to maintain such columns and ensure they're correct. As noted, the general idea in being globally competitive is being able to attract people regardless of where they live. As shown by the Stack Overflow calculator, this doesn't necessarily mean offering location-indepedent salaries.

**Comment by TehShrike** [comment]
Without something concrete like salary ranges, there's no guidance/oversight on the current column, and no way for anyone to form a meaningful idea of what the current column represents.

I think this table would be more useful/less confusing without the "globally-competitive compensation" column.

**Comment by TehShrike** [comment]
Maybe that column is useful to people in NY or CA who can use it to ignore anything without a checkmark, but to anyone else, that column is pretty meaningless without another column telling you what regions the company *is* competitive in.

**Comment by yanirs** [comment]
@TehShrike I'm not based in NY or CA and @Khrol isn't based there either, but the column is useful for us. Regardless of where you're based, you're better off going with a company that offers globally competitive salaries rather than one that doesn't.
